# Generated by Django 3.2.6 on 2021-09-05 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0002_auto_20210905_1735'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pregunta',
            name='fecha',
        ),
        migrations.RemoveField(
            model_name='pregunta',
            name='puntaje_total',
        ),
        migrations.AddField(
            model_name='pregunta',
            name='max_puntaje',
            field=models.DecimalField(decimal_places=2, default=5, max_digits=6, verbose_name='Maximo Puntaje'),
        ),
    ]
